services:
  backend:
    build: ./school-management-be
    container_name: school-backend
    environment:
      - DATABASE_URL=postgresql://postgres:schoolDB1@72.61.215.205:5432/school_management
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=7d
      - PORT=3000
      - NODE_ENV=production
      - CORS_ORIGIN=https://be.sunflowerskg.com
      - CORS_ORIGIN=https://sunflowerskg.com
      - CORS_ORIGIN=localhost:4200
    ports:
      - "3000:3000"
    volumes:
      - gallery-uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./school-management
    container_name: school-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  gallery-uploads:
